### PR TITLE
Use Eval to run tests, instead of Neko.

### PR DESCRIPTION
**Pull request by player-03**
[Eval](https://haxe.org/blog/eval/) is Haxe's new(ish) interpreter, with various improvements over Neko that barely matter for such a small test suite. Mainly I'm suggesting this because Neko is no longer maintained.

### CODE REVIEW

**Comment by player-03** [comment]
Ugh, it still submitted this to the master branch. Consider switching the default branch?

**Comment by paulsgcross** [comment]
> Ugh, it still submitted this to the master branch. Consider switching the default branch?

Sure thing

**Review by paulsgcross — APPROVED** [review]
Sensible to use a target that is maintained.

Actually, I had no idea `-x` targetted Neko as I used a basic example for the `test.hxml` originally. Very useful to know going forward :)

**Comment by player-03** [comment]
I didn't recognize the option either, so I looked it up.

> `-x <file>` Shortcut for compiling and executing a Neko file.

**Pull request merged**
